/*


  Replace this file with the C code generated by:
  https://realtimelogic.info/htmla/

  See the following tutorial for details on how to use the above service:
  https://realtimelogic.com/blog/2018/11/Creating-SinglePage-Apps-with-the-Minnow-Server


*/

#include <MSLib.h>

int
fetchPage(void* hndl, MST* mst, U8* path)
{
   (void)hndl;
   (void)mst;
   (void)path;
   return 0; /* Page not found (404) */
}

